### ISSUE TITLE
Enable the Deletion and editing of the existing posts.

### ISSUE THREAD

**Issue by atb00ker** [ATB00ker/theAmityAndroidClub#7]
Currently once a post is made, user cannot delete or edit it, the feature needs to be introduced.

**Comment by ATB00ker** [comment]
6ecd8e9d9147b5926368ebdd7c87e411f1b509db

**Comment by atb00ker** [comment]
Solved in commit: 6ecd8e9d9147b5926368ebdd7c87e411f1b509db
